CREATE TABLE IF NOT EXISTS characters (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  age INTEGER,
  role TEXT NOT NULL DEFAULT '',
  job TEXT NOT NULL DEFAULT '',
  hometown TEXT NOT NULL DEFAULT '',
  summary TEXT NOT NULL DEFAULT '',
  tagline TEXT NOT NULL DEFAULT '',
  bio TEXT NOT NULL DEFAULT '[]',
  camera_presence TEXT NOT NULL DEFAULT '',
  story_arc TEXT NOT NULL DEFAULT '',
  accent_color TEXT NOT NULL DEFAULT '#D4A574',
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS episodes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  number INTEGER UNIQUE NOT NULL,
  title TEXT NOT NULL,
  runtime TEXT NOT NULL DEFAULT '45 minutes',
  logline TEXT NOT NULL DEFAULT '',
  cold_open TEXT NOT NULL DEFAULT '{}',
  acts TEXT NOT NULL DEFAULT '[]',
  key_scenes TEXT NOT NULL DEFAULT '[]',
  themes TEXT NOT NULL DEFAULT '[]',
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS production_sections (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL DEFAULT '[]',
  is_final_statement INTEGER NOT NULL DEFAULT 0,
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS page_meta (
  id TEXT PRIMARY KEY,
  section_label TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL DEFAULT '',
  subtitle TEXT NOT NULL DEFAULT ''
);
